### ISSUE TITLE
Problem with autoindent

### ISSUE THREAD

**Issue by ocie** [Cwright017/atom-language-brightscript#1]
I'm having a problem getting the autoindent to work.  I'm not sure if it is my setup or the language plugin.  If I enter a simple function like the following 

```
function foo()
    x=2
end function
```

Atom will not automatically indent the function body, and if I add the indentation myself, autoindent  will remove the indentation and put the "x=2" at the first column.  If I add another line below the "x=2", atom will continue to use this indentation level.

**Comment by ocie** [comment]
I think I have a solution and submitted you a pull request for the change.

**Comment by cwright017** [comment]
Merged, thanks 👍
